In [5]:
import pandas as pd
df = pd.read_csv("student_exam_performance.csv")

In [6]:
df.head()

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail

In [7]:
df.shape

(10, 12)

In [8]:
df.tail()

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass

In [9]:
df.columns

Index(['Student_ID', 'Gender', 'Age', 'Study_Hours_Per_Week',
       'Attendance_Percentage', 'Previous_Score', 'Parental_Education_Level',
       'Internet_Access', 'Extracurricular_Activities', 'Sleep_Hours',
       'Final_Exam_Score', 'Pass_Fail'],
      dtype='str')

In [10]:
df.dtypes

Student_ID                      str
Gender                          str
Age                           int64
Study_Hours_Per_Week          int64
Attendance_Percentage         int64
Previous_Score                int64
Parental_Education_Level        str
Internet_Access                 str
Extracurricular_Activities      str
Sleep_Hours                   int64
Final_Exam_Score              int64
Pass_Fail                       str
dtype: object

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  10 non-null     str
 1   Gender                      10 non-null     str
 2   Age                         10 non-null     int64
 3   Study_Hours_Per_Week        10 non-null     int64
 4   Attendance_Percentage       10 non-null     int64
 5   Previous_Score              10 non-null     int64
 6   Parental_Education_Level    10 non-null     str
 7   Internet_Access             10 non-null     str
 8   Extracurricular_Activities  10 non-null     str
 9   Sleep_Hours                 10 non-null     int64
 10  Final_Exam_Score            10 non-null     int64
 11  Pass_Fail                   10 non-null     str
dtypes: int64(6), str(6)
memory usage: 1.1 KB

In [12]:
df.describe()

,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Sleep_Hours,Final_Exam_Score
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.00000
mean,17.000000,12.500000,83.000000,70.100000,6.800000,71.80000
std,0.816497,4.949747,10.677078,11.189777,1.032796,14.46682
min,16.000000,5.000000,65.000000,55.000000,5.000000,49.00000
25%,16.250000,8.500000,74.000000,61.250000,6.000000,60.25000
50%,17.000000,13.000000,86.500000,69.000000,7.000000,74.00000
75%,17.750000,15.750000,91.500000,77.000000,7.750000,81.75000
max,18.000000,20.000000,95.000000,88.000000,8.000000,90.00000

In [13]:
df["Age"].mean()

np.float64(17.0)

In [14]:
df["Age"].median()

np.float64(17.0)

In [15]:
df["Age"].mode()

0    17
Name: Age, dtype: int64

In [16]:
df["Age"].var()

np.float64(0.6666666666666666)

In [17]:
df["Age"].std()

np.float64(0.816496580927726)

In [18]:
df["Age"].max()

np.int64(18)

In [19]:
df["Age"].min()

np.int64(16)

In [20]:
df["Age"].count()

np.int64(10)

In [21]:
df["Age"].unique()

array([17, 16, 18])

In [22]:
df["Age"].nunique()

3

In [23]:
df["Age"].value_counts()

Age
17    4
16    3
18    3
Name: count, dtype: int64

In [25]:
df.isnull()

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False

In [26]:
df.isnull().sum()

Student_ID                    0
Gender                        0
Age                           0
Study_Hours_Per_Week          0
Attendance_Percentage         0
Previous_Score                0
Parental_Education_Level      0
Internet_Access               0
Extracurricular_Activities    0
Sleep_Hours                   0
Final_Exam_Score              0
Pass_Fail                     0
dtype: int64

In [27]:
df.isnull().mean()*100

Student_ID                    0.0
Gender                        0.0
Age                           0.0
Study_Hours_Per_Week          0.0
Attendance_Percentage         0.0
Previous_Score                0.0
Parental_Education_Level      0.0
Internet_Access               0.0
Extracurricular_Activities    0.0
Sleep_Hours                   0.0
Final_Exam_Score              0.0
Pass_Fail                     0.0
dtype: float64

In [28]:
df.dropna()

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass

In [30]:
df.fillna(0)

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass

In [31]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
import os
os.getcwd()

'C:\\Users\\user\\4NI25CI004'

In [34]:
df.drop_duplicates()

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass

In [35]:
df["Gender"]

0      Male
1    Female
2      Male
3    Female
4      Male
5    Female
6      Male
7    Female
8      Male
9    Female
Name: Gender, dtype: str

In [37]:
df[["Gender","Age"]]

   Gender  Age
0    Male   17
1  Female   16
2    Male   18
3  Female   17
4    Male   16
5  Female   18
6    Male   17
7  Female   16
8    Male   18
9  Female   17

In [38]:
df.iloc[0:5]

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail

In [40]:
df[df["Age"]>17]

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail

In [42]:
df.sort_values("Age")

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail

In [43]:
df.rename(columns={"Age":"Age_Years"})

,Student_ID,Gender,Age_Years,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass

In [56]:
df["New_Score"]=df["Previous_Score"]+10

In [58]:
df.drop("New_Score",axis=1)

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail,Bonus,CGPA
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass,7.157895,7.157895
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass,7.789474,7.789474
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail,6.315789,6.315789
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass,9.263158,9.263158
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail,5.789474,5.789474
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass,7.368421,7.368421
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass,6.842105,6.842105
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass,8.947368,8.947368
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail,6.105263,6.105263
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass,8.210526,8.210526

In [59]:
df.drop(["Bonus", "CGPA"], axis=1, inplace=True)

In [60]:
df.head()

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail,New_Score
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass,78
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass,84
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail,70
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass,98
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail,65

In [61]:
df.groupby("Internet_Access")

In [62]:
df.groupby("Internet_Access")["Age"].mean()

Internet_Access
No     17.333333
Yes    16.857143
Name: Age, dtype: float64

In [64]:
df1=df.iloc[:5]
df2=df.iloc[5:]

In [65]:
df1.head()

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail,New_Score
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass,78
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass,84
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail,70
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass,98
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail,65

In [66]:
df2.head()

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail,New_Score
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass,80
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass,75
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass,95
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail,68
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass,88

In [67]:
pd.concat([df1,df2])

,Student_ID,Gender,Age,Study_Hours_Per_Week,Attendance_Percentage,Previous_Score,Parental_Education_Level,Internet_Access,Extracurricular_Activities,Sleep_Hours,Final_Exam_Score,Pass_Fail,New_Score
0,S001,Male,17,12,85,68,Bachelor,Yes,Yes,7,72,Pass,78
1,S002,Female,16,15,92,74,Master,Yes,No,8,81,Pass,84
2,S003,Male,18,8,70,60,High School,No,Yes,6,58,Fail,70
3,S004,Female,17,20,95,88,Master,Yes,Yes,8,90,Pass,98
4,S005,Male,16,5,65,55,High School,No,No,5,49,Fail,65
5,S006,Female,18,14,88,70,Bachelor,Yes,Yes,7,76,Pass,80
6,S007,Male,17,10,80,65,Bachelor,Yes,No,6,67,Pass,75
7,S008,Female,16,18,93,85,Master,Yes,Yes,8,89,Pass,95
8,S009,Male,18,7,72,58,High School,No,Yes,6,54,Fail,68
9,S010,Female,17,16,90,78,Bachelor,Yes,No,7,82,Pass,88